// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gdal_warp_nara
List gdal_warp_nara(CharacterVector dsn, CharacterVector target_crs, NumericVector target_extent, IntegerVector target_dim, NumericVector target_res, IntegerVector bands, CharacterVector resample, LogicalVector silent, CharacterVector band_output_type, CharacterVector options, CharacterVector dsn_outname, LogicalVector include_meta);
RcppExport SEXP _gdalnara_gdal_warp_nara(SEXP dsnSEXP, SEXP target_crsSEXP, SEXP target_extentSEXP, SEXP target_dimSEXP, SEXP target_resSEXP, SEXP bandsSEXP, SEXP resampleSEXP, SEXP silentSEXP, SEXP band_output_typeSEXP, SEXP optionsSEXP, SEXP dsn_outnameSEXP, SEXP include_metaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type dsn(dsnSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type target_crs(target_crsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type target_extent(target_extentSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type target_dim(target_dimSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type target_res(target_resSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type bands(bandsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type resample(resampleSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type silent(silentSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type band_output_type(band_output_typeSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type options(optionsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type dsn_outname(dsn_outnameSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type include_meta(include_metaSEXP);
    rcpp_result_gen = Rcpp::wrap(gdal_warp_nara(dsn, target_crs, target_extent, target_dim, target_res, bands, resample, silent, band_output_type, options, dsn_outname, include_meta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gdalnara_gdal_warp_nara", (DL_FUNC) &_gdalnara_gdal_warp_nara, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_gdalnara(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
